Handle unsuccessful load of savedModel
MTG/essentia pull request #1214
Opened 2021-12-30 10:13 UTC by palonso

Throw an exception if a `savedModel` is not loaded successfully.
This solution mimics the way we handle unsuccessful load of protocol buffers (`graphFilename`)

2021-12-30 10:23 UTC, palonso commented
@dbogdanov, two questions:
Tensorflow [calls](https://www.tensorflow.org/guide/saved_model) the format `SavedModel`. Our parameter is called `savedModel` to follow the convention of starting with lowercase. I'm using `SavedModel` to refer to the format and `savedModel` for the parameter. Is this misleading?

The derivate algorithms (e.g., `TensorflowPredictMusiCNN`) have similar `testInvalidParam` that I haven't updated, as they just rely on `TensorflowPredict` and that's already tested. Do you think it makes sense to keep this test redundancy, or should I just remove the additional tests in a separate PR?

2022-01-25 17:50 UTC, dbogdanov commented
In such cases, we could use dummy tests (e.g., `testDummyInvalidParam`) covering redundant tests, with a comment about algorithm dependencies and where the test is covered in the source code for the test.

2022-01-25 17:53 UTC, dbogdanov requested changes

2022-01-25 17:53 UTC, dbogdanov commented on src/algorithms/machinelearning/tensorflowpredict.cpp
> +        throw EssentiaException("TensorflowPredict: Error importing SavedModel. ", TF_Message(_status));
Following your comment, maybe we can explicitly say "...SavedModel specified in the `_savedModel` parameter." to avoid any confusion.

2022-01-28 14:37 UTC, merged