Implementation of the the FSD-SINet family of models
MTG/essentia pull request #1300
Opened 2023-01-27 10:49 UTC by palonso

This PR addresses the implementation of the algorithm required to use the FSD-SINet models by @edufonseca.
It merges three branches where different features required to reproduce the mel-spectrogram parametrization were implemented (#1296, #1297, #1298) so if we decide to address all the changes here at once these PRs could be closed.

One of the limitations to reproduce the original implementation is that, by default, Essentia operates with floats instead of doubles. This has some impact in regression of mel-spectrograms (relative error ~1e-1) but it doesn't affect much the predictions by the model (relative error ~1e-4).

Another note is that the clip-wise audio normalization is only implemented in standard mode since in real-time applications it is not possible to access the entire signal beforehand.

2023-02-09 23:44 UTC, dbogdanov requested changes

2023-02-09 23:44 UTC, dbogdanov commented on src/algorithms/machinelearning/tensorflowpredictfsdsinet.cpp
> +  "Note II: The FSD-SINet models were trained on normalized audio clips. "
Keeping simply "Note:" for any amount of notes maybe OK for a cleaner look.

2023-02-09 23:44 UTC, dbogdanov commented on src/algorithms/machinelearning/tensorflowpredictfsdsinet.cpp
> +  "In this case, it is the responsibility of the user to feed the algorithm with audio featuring a healthy dynamic range.\n\n"
It is not clear what is the "healthy" range that is expected. Can it be more concrete?

2023-02-09 23:44 UTC, dbogdanov commented on src/algorithms/machinelearning/tensorflowpredictfsdsinet.cpp
> +// todo: refer also the github repository if it is updated with the source code https://github.com/edufonseca/shift_sec
Outdated comment?

2023-02-09 23:44 UTC, dbogdanov commented on src/algorithms/standard/windowing.cpp
>    _constantsDecimals = parameter("constantsDecimals").toInt();
Duplicate line leftover from merging conflicts.

2023-02-09 23:44 UTC, dbogdanov commented on src/algorithms/standard/windowing.h
> +  bool _splitPadding;
Duplicate line leftover from merging conflicts.

2023-02-09 23:44 UTC, dbogdanov commented on src/algorithms/machinelearning/tensorflowpredictfsdsinet.cpp
> +  if (!signal->size()) {
Could be done before normalize

2023-02-09 23:44 UTC, dbogdanov commented on test/src/unittests/spectral/test_tensorflowinputfsdsinet.py
> +        # Essentia generates and additional frame because of its zero-padding strategy.
"an additional frame"

2023-02-10 10:24 UTC, palonso commented on doc/sphinxdoc/models.rst
> +* ``fsd-sinet-vgg41-tlpf-ibp`` [`weights <https://essentia.upf.edu/models/audio-event-recognition/fsd-sinet/fsd-sinet-vgg41-tlpf-ibp-1.pb>`_, `metadata <https://essentia.upf.edu/models/audio-event-re
that's a good idea. I'll work on that

2023-02-17 15:34 UTC, dbogdanov requested changes

2023-02-17 15:34 UTC, dbogdanov commented on src/algorithms/machinelearning/tensorflowpredictfsdsinet.cpp
> +  m"  [2] https://github.com/edufonseca/shift_sec"
Misspell char `m`.

2023-02-17 15:41 UTC, merged