Add changes to support building arm64 macos wheels
MTG/essentia pull request #1383
Opened 2023-10-24 16:16 UTC by palonso

In theory, Apple Silicon wheels can be cross-compiled from the intel mac machines (however the can't be tested):
https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon

Additionally, we replace `os.system` calls by `subprocess.run` so that we can notice when one of these subprocesses fail.

2023-10-24 16:43 UTC, dbogdanov requested changes

2023-10-24 16:43 UTC, dbogdanov commented on pyproject-tensorflow.toml
> +select = "*arm64*"
Make the override `select` more specific so that it only triggers macos builds (to avoid a conflict with future arm64 Linux builds).

2023-10-24 17:03 UTC, dbogdanov commented
> In theory, Apple Silicon wheels can be cross-compiled from the intel mac machines (however the can't be tested).
I thinks this won't work because we rely on homebrew to install dependencies (and those would still be x86).

2023-10-25 07:31 UTC, palonso commented
> > In theory, Apple Silicon wheels can be cross-compiled from the intel mac machines (however the can't be tested).
> 
> I think this won't work because we rely on homebrew to install dependencies (and those would still be x86).

You are right. I was exploring [this hack](https://github.com/orgs/Homebrew/discussions/2843?sort=top#discussioncomment-2026915) to force installing arm64 libs for the cross-build case.

2024-02-01 16:08 UTC, palonso commented
After the release of the native arm64 MacOS worker ([macos-14](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/)), this PR has been updated to use it directly instead of to cross-compiling from an intel machine.

Main changes:
- Add `macos-14` worker for arm64 based (M*) MacOS wheels
- Bump the Intel MacOS builds `macos-11` [[deprecated](https://github.com/actions/runner-images/tree/main?tab=readme-ov-file#available-images)] -> `macos-12`
- Bump Actions checkout, and upload-artifact from `v3` -> `v4`, so they use node 20 instead of node 16 (that will reach the end of life [by Spring 2024](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)).
- Bump cibuildwheels `11.4` -> `16.5` which internally upgrades `setup-python` to use node 20 instead of 16 and supports building wheels for Python 3.12.
- Manually copy libSLD2 dylibs into macos-14 wheels to prevent crashes (#1325).

2024-02-08 15:07 UTC, dbogdanov commented
There is an error in building the arm64 essentia-tensorflow wheels for MacOS. The `artifact-macos-14-pyproject-tensorflow.zip` contains files for main esssentia instead (e.g., `essentia-2.1b6.dev1161-cp310-cp310-macosx_11_0_arm64.whl`)

2024-02-08 15:13 UTC, dbogdanov requested changes

2024-02-08 15:13 UTC, dbogdanov commented on pyproject-tensorflow.toml
> +environment = { PROJECT_NAME="essentia", ESSENTIA_PROJECT_NAME="${PROJECT_NAME}", ESSENTIA_WHEEL_SKIP_3RDPARTY=1, ESSENTIA_WHEEL_ONLY_PYTHON=1, ESSENTIA_MACOSX_ARM64=1 }
wrong project name, creates wrong wheel names.

2024-02-14 18:45 UTC, merged